#!/usr/bin/env node
/**
 * Interactive setup wizard for GitHub Portfolio Analyzer
 * Run: node setup.js
 */
const fs = require('fs');
const path = require('path');
const readline = require('readline');
const crypto = require('crypto');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(res => rl.question(q, res));

function randomSecret(len = 48) {
  return crypto.randomBytes(len).toString('base64').slice(0, len);
}

async function main() {
  console.log('\n🚀 GitHub Portfolio Analyzer — Setup Wizard\n');
  console.log('Press Enter to keep defaults (shown in brackets)\n');

  const port = (await ask('Port [5000]: ')).trim() || '5000';
  const mongoUri = (await ask('MongoDB URI [mongodb://localhost:27017/gpa]: ')).trim() || 'mongodb://localhost:27017/gpa';
  const githubClientId = (await ask('GitHub OAuth Client ID (leave blank to skip): ')).trim();
  const githubClientSecret = githubClientId ? (await ask('GitHub OAuth Client Secret: ')).trim() : '';
  const appUrl = (await ask(`App URL [http://localhost:${port}]: `)).trim() || `http://localhost:${port}`;
  const githubToken = (await ask('GitHub API Token (optional, increases rate limit): ')).trim();
  const openaiKey = (await ask('OpenAI API Key (optional, enables AI features): ')).trim();

  const jwtSecret = randomSecret();
  const jwtRefreshSecret = randomSecret();

  const envContent = `# Auto-generated by setup.js on ${new Date().toISOString()}
NODE_ENV=development
PORT=${port}
LOG_LEVEL=info
CORS_ORIGIN=${appUrl}
APP_URL=${appUrl}

MONGODB_URI=${mongoUri}

JWT_SECRET=${jwtSecret}
JWT_REFRESH_SECRET=${jwtRefreshSecret}
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=30d

GITHUB_CLIENT_ID=${githubClientId}
GITHUB_CLIENT_SECRET=${githubClientSecret}
GITHUB_CALLBACK_URL=${appUrl}/api/auth/github/callback
OAUTH_SUCCESS_REDIRECT=/
OAUTH_FAILURE_REDIRECT=/?oauth=failed

GITHUB_TOKEN=${githubToken}

OPENAI_API_KEY=${openaiKey}

CACHE_TTL_SECONDS=300
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX=120
`;

  const envPath = path.join(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    const overwrite = await ask('\n.env already exists. Overwrite? [y/N]: ');
    if (!overwrite.toLowerCase().startsWith('y')) {
      console.log('Skipped. Your existing .env was not changed.');
      rl.close();
      return;
    }
  }

  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ .env file created successfully!');

  if (!githubClientId) {
    console.log('\n⚠️  GitHub OAuth not configured. To enable "Continue with GitHub":');
    console.log('   1. Go to https://github.com/settings/applications/new');
    console.log(`   2. Set callback URL to: ${appUrl}/api/auth/github/callback`);
    console.log('   3. Run this setup again with the Client ID and Secret');
  }

  console.log('\n📦 Next steps:');
  console.log('   npm install');
  console.log('   npm start');
  console.log(`   Open: ${appUrl}\n`);
  rl.close();
}

main().catch(e => { console.error(e); process.exit(1); });
